package doctor.domain

case class Champion(name: String, key: String)

object Champion {
  val Champions = Map(
    1 -> Champion("애니","Annie"),
    2 -> Champion("올라프","Olaf"),
    3 -> Champion("갈리오","Galio"),
    4 -> Champion("트위스티드 페이트","TwistedFate"),
    5 -> Champion("신 짜오","XinZhao"),
    6 -> Champion("우르곳","Urgot"),
    7 -> Champion("르블랑","Leblanc"),
    8 -> Champion("블라디미르","Vladimir"),
    9 -> Champion("피들스틱","FiddleSticks"),
    10 -> Champion("케일","Kayle"),
    11 -> Champion("마스터 이","MasterYi"),
    12 -> Champion("알리스타","Alistar"),
    13 -> Champion("라이즈","Ryze"),
    14 -> Champion("사이온","Sion"),
    15 -> Champion("시비르","Sivir"),
    16 -> Champion("소라카","Soraka"),
    17 -> Champion("티모","Teemo"),
    18 -> Champion("트리스타나","Tristana"),
    19 -> Champion("워윅","Warwick"),
    20 -> Champion("누누","Nunu"),
    21 -> Champion("미스 포츈","MissFortune"),
    22 -> Champion("애쉬","Ashe"),
    23 -> Champion("트린다미어","Tryndamere"),
    24 -> Champion("잭스","Jax"),
    25 -> Champion("모르가나","Morgana"),
    26 -> Champion("질리언","Zilean"),
    27 -> Champion("신지드","Singed"),
    28 -> Champion("이블린","Evelynn"),
    29 -> Champion("트위치","Twitch"),
    30 -> Champion("카서스","Karthus"),
    31 -> Champion("초가스","Chogath"),
    32 -> Champion("아무무","Amumu"),
    33 -> Champion("람머스","Rammus"),
    34 -> Champion("애니비아","Anivia"),
    35 -> Champion("샤코","Shaco"),
    36 -> Champion("문도 박사","DrMundo"),
    37 -> Champion("소나","Sona"),
    38 -> Champion("카사딘","Kassadin"),
    39 -> Champion("이렐리아","Irelia"),
    40 -> Champion("잔나","Janna"),
    41 -> Champion("갱플랭크","Gangplank"),
    42 -> Champion("코르키","Corki"),
    43 -> Champion("카르마","Karma"),
    44 -> Champion("타릭","Taric"),
    45 -> Champion("베이가","Veigar"),
    48 -> Champion("트런들","Trundle"),
    50 -> Champion("스웨인","Swain"),
    51 -> Champion("케이틀린","Caitlyn"),
    53 -> Champion("블리츠크랭크","Blitzcrank"),
    54 -> Champion("말파이트","Malphite"),
    55 -> Champion("카타리나","Katarina"),
    56 -> Champion("녹턴","Nocturne"),
    57 -> Champion("마오카이","Maokai"),
    58 -> Champion("레넥톤","Renekton"),
    59 -> Champion("자르반 4세","JarvanIV"),
    60 -> Champion("엘리스","Elise"),
    61 -> Champion("오리아나","Orianna"),
    62 -> Champion("오공","MonkeyKing"),
    63 -> Champion("브랜드","Brand"),
    64 -> Champion("리 신","LeeSin"),
    67 -> Champion("베인","Vayne"),
    68 -> Champion("럼블","Rumble"),
    69 -> Champion("카시오페아","Cassiopeia"),
    72 -> Champion("스카너","Skarner"),
    74 -> Champion("하이머딩거","Heimerdinger"),
    75 -> Champion("나서스","Nasus"),
    76 -> Champion("니달리","Nidalee"),
    77 -> Champion("우디르","Udyr"),
    78 -> Champion("뽀삐","Poppy"),
    79 -> Champion("그라가스","Gragas"),
    80 -> Champion("판테온","Pantheon"),
    81 -> Champion("이즈리얼","Ezreal"),
    82 -> Champion("모데카이저","Mordekaiser"),
    83 -> Champion("요릭","Yorick"),
    84 -> Champion("아칼리","Akali"),
    85 -> Champion("케넨","Kennen"),
    86 -> Champion("가렌","Garen"),
    89 -> Champion("레오나","Leona"),
    90 -> Champion("말자하","Malzahar"),
    91 -> Champion("탈론","Talon"),
    92 -> Champion("리븐","Riven"),
    96 -> Champion("코그모","KogMaw"),
    98 -> Champion("쉔","Shen"),
    99 -> Champion("럭스","Lux"),
    101 -> Champion("제라스","Xerath"),
    102 -> Champion("쉬바나","Shyvana"),
    103 -> Champion("아리","Ahri"),
    104 -> Champion("그레이브즈","Graves"),
    105 -> Champion("피즈","Fizz"),
    106 -> Champion("볼리베어","Volibear"),
    107 -> Champion("렝가","Rengar"),
    110 -> Champion("바루스","Varus"),
    111 -> Champion("노틸러스","Nautilus"),
    112 -> Champion("빅토르","Viktor"),
    113 -> Champion("세주아니","Sejuani"),
    114 -> Champion("피오라","Fiora"),
    115 -> Champion("직스","Ziggs"),
    117 -> Champion("룰루","Lulu"),
    119 -> Champion("드레이븐","Draven"),
    120 -> Champion("헤카림","Hecarim"),
    121 -> Champion("카직스","Khazix"),
    122 -> Champion("다리우스","Darius"),
    126 -> Champion("제이스","Jayce"),
    127 -> Champion("리산드라","Lissandra"),
    131 -> Champion("다이애나","Diana"),
    133 -> Champion("퀸","Quinn"),
    134 -> Champion("신드라","Syndra"),
    143 -> Champion("자이라","Zyra"),
    150 -> Champion("나르","Gnar"),
    154 -> Champion("자크","Zac"),
    157 -> Champion("야스오","Yasuo"),
    161 -> Champion("벨코즈","Velkoz"),
    201 -> Champion("브라움","Braum"),
    222 -> Champion("징크스","Jinx"),
    223 -> Champion("탐 켄치","TahmKench"),
    236 -> Champion("루시안","Lucian"),
    238 -> Champion("제드","Zed"),
    245 -> Champion("에코","Ekko"),
    254 -> Champion("바이","Vi"),
    266 -> Champion("아트록스","Aatrox"),
    267 -> Champion("나미","Nami"),
    268 -> Champion("아지르","Azir"),
    412 -> Champion("쓰레쉬","Thresh"),
    421 -> Champion("렉사이","RekSai"),
    429 -> Champion("칼리스타","Kalista"),
    432 -> Champion("바드","Bard")
  )

  def findBy(id: Int) = Champions.get(id)
}